version: '3.8'
services:
  server:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
    networks:
      - custom
    restart: always

  postgres_db:
    image: postgres
    container_name: postgres_db
    volumes:
      - ./postgres-data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - custom

volumes:
  postgres_data:

networks:
  custom:
    driver: bridge