"""add money amount column into operations table

Revision ID: bda1fce5c8d2
Revises: 
Create Date: 2023-02-22 02:37:28.243699

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bda1fce5c8d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('operation',
    sa.Column('operation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'SUCCEEDED', 'FAILED', name='operationstatus'), nullable=True),
    sa.Column('type', sa.Enum('PAYIN', 'TRANSFER', 'PAYOUT', name='operationtype'), nullable=True),
    sa.Column('money_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('operation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    op.drop_table('user')
    # ### end Alembic commands ###
